<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $movies = [
            [
                'title' => 'Inception',
                'description' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
                'year' => '2010',
                'genre' => 'Khoa học viễn tưởng',
                'director' => 'Christopher Nolan',
                'created_at' => now(),
                'updated_at' => now(),
                'avg_rating' => 4.50,
                'poster_url' => 'images/posters/inception_poster.jpg',
                'trailer_url' => 'https://example.com/inception-trailer.mp4',
            ],
            [
                'title' => 'The Dark Knight',
                'description' => 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
                'year' => '2008',
                'director' => 'Christopher Nolan',
                'genre' => 'Hành động',
                'created_at' => now(),
                'updated_at' => now(),
                'avg_rating' => 4.75,
                'poster_url' => 'images/posters/The_Dark_Knight_poster.jpg',
                'trailer_url' => 'https://example.com/dark-knight-trailer.mp'
            ],
            [
                'title' => 'Interstellar',
                'description' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.',
                'year' => '2014',
                'genre' => 'phiêu lưu',
                'director' => 'Christopher Nolan',
                'created_at' => now(),
                'updated_at' => now(),
                'avg_rating' => 4.60,
                'poster_url' => 'images/posters/Interstellar_poster.jpg',
                'trailer_url' => 'https://example.com/interstellar-trailer.mp4',
            ],
            [
                'title' => 'Tenet',
                'description' => 'Armed with only one word—Tenet—and fighting for the survival of the entire world, a protagonist journeys through a twilight world of international espionage.',
                'year' => '2020',
                'genre' => 'Hành động, Khoa học viễn tưởng',
                'director' => 'Christopher Nolan',
                'created_at' => now(),
                'updated_at' => now(),
                'avg_rating' => 4.2,
                'poster_url' => 'images/posters/tenet.jpg',
                'trailer_url' => 'https://example.com/tenet-trailer.mp4',
                
            ],
            [
                'title' => 'Avatar',
                'description' => 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
                'year' => '2009',
                'genre' => 'Khoa học viễn tưởng',
                'director' => 'James Cameron',
                'avg_rating' => 4.7,
                'poster_url' => 'images/posters/avatar.jpg',
                'trailer_url' => 'https://example.com/avatar-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Titanic',
                'description' => 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
                'year' => '1997',
                'genre' => 'Tình cảm',
                'director' => 'James Cameron',
                'avg_rating' => 4.8,
                'poster_url' => 'images/posters/titanic.jpg',
                'trailer_url' => 'https://example.com/titanic-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Matrix',
                'description' => 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
                'year' => '1999',
                'genre' => 'Hành động, Khoa học viễn tưởng',
                'director' => 'The Wachowskis',
                'avg_rating' => 4.6,
                'poster_url' => 'images/posters/matrix.jpg',
                'trailer_url' => 'https://example.com/matrix-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Shawshank Redemption',
                'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'year' => '1994',
                'genre' => 'Tâm lý',
                'director' => 'Frank Darabont',
                'avg_rating' => 4.9,
                'poster_url' => 'images/posters/shawshank.jpg',
                'trailer_url' => 'https://example.com/shawshank-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Forrest Gump',
                'description' => 'The story of Forrest Gump, a man with a low IQ who achieved extraordinary things in his life.',
                'year' => '1994',
                'genre' => 'Tâm lý, Hài hước',
                'director' => 'Robert Zemeckis',
                'avg_rating' => 4.8,
                'poster_url' => 'images/posters/forrestgump.jpg',
                'trailer_url' => 'https://example.com/forrestgump-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Gladiator',
                'description' => 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.',
                'year' => '2000',
                'genre' => 'Hành động, Lịch sử',
                'director' => 'Ridley Scott',
                'avg_rating' => 4.5,
                'poster_url' => 'images/posters/gladiator.jpg',
                'trailer_url' => 'https://example.com/gladiator-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Joker',
                'description' => 'In Gotham City, a mentally troubled comedian embarks on a downward spiral of social revolution and bloody crime.',
                'year' => '2019',
                'genre' => 'Tâm lý, Tội phạm',
                'director' => 'Todd Phillips',
                'avg_rating' => 4.4,
                'poster_url' => 'images/posters/joker.jpg',
                'trailer_url' => 'https://example.com/joker-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Paradise',
                'description' => 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
                'year' => '2019',
                'genre' => 'Tâm lý, Kịch tính',
                'director' => 'Bong Joon Ho',
                'avg_rating' => 4.6,
                'poster_url' => 'images/posters/parasite.jpg',
                'trailer_url' => 'https://example.com/parasite-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Avengers: Endgame',
                'description' => 'After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos\' actions and restore balance to the universe.',
                'year' => '2019',
                'genre' => 'Hành động, Siêu anh hùng',
                'director' => 'Anthony & Joe Russo',
                'avg_rating' => 4.7,
                'poster_url' => 'images/posters/endgame.jpg',
                'trailer_url' => 'https://example.com/endgame-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Black Panther',
                'description' => 'T\'Challa returns home to Wakanda to take his rightful place as king after his father\'s death.',
                'year' => '2018',
                'genre' => 'Siêu anh hùng',
                'director' => 'Ryan Coogler',
                'avg_rating' => 4.3,
                'poster_url' => 'images/posters/blackpanther.jpg',
                'trailer_url' => 'https://example.com/blackpanther-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Doctor Strange',
                'description' => 'While on a journey of physical and spiritual healing, a brilliant neurosurgeon discovers the hidden world of magic.',
                'year' => '2016',
                'genre' => 'Siêu anh hùng, Khoa học viễn tưởng',
                'director' => 'Scott Derrickson',
                'avg_rating' => 4.2,
                'poster_url' => 'images/posters/doctorstrange.jpg',
                'trailer_url' => 'https://example.com/doctorstrange-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Iron Man',
                'description' => 'After being held captive, an industrialist builds a high-tech suit of armor to escape and becomes the superhero Iron Man.',
                'year' => '2008',
                'genre' => 'Siêu anh hùng, Hành động',
                'director' => 'Jon Favreau',
                'avg_rating' => 4.4,
                'poster_url' => 'images/posters/ironman.jpg',
                'trailer_url' => 'https://example.com/ironman-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Spider-Man: No Way Home',
                'description' => 'Peter Parker seeks Doctor Strange’s help to restore his secret identity, but things quickly go out of control.',
                'year' => '2021',
                'genre' => 'Siêu anh hùng',
                'director' => 'Jon Watts',
                'avg_rating' => 4.5,
                'poster_url' => 'images/posters/spiderman.jpg',
                'trailer_url' => 'https://example.com/spiderman-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dune',
                'description' => 'A noble family becomes embroiled in a war for control over the galaxy’s most valuable asset while its heir becomes troubled by visions of a dark future.',
                'year' => '2021',
                'genre' => 'Khoa học viễn tưởng',
                'director' => 'Denis Villeneuve',
                'avg_rating' => 4.3,
                'poster_url' => 'images/posters/dune.jpg',
                'trailer_url' => 'https://example.com/dune-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Oppenheimer',
                'description' => 'The story of J. Robert Oppenheimer and his role in the development of the atomic bomb.',
                'year' => '2023',
                'genre' => 'Tiểu sử, Lịch sử',
                'director' => 'Christopher Nolan',
                'avg_rating' => 4.8,
                'poster_url' => 'images/posters/oppenheimer.jpg',
                'trailer_url' => 'https://example.com/oppenheimer-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Barbie',
                'description' => 'Barbie suffers a crisis that leads her to question her world and her existence.',
                'year' => '2023',
                'genre' => 'Hài hước, Phiêu lưu',
                'director' => 'Greta Gerwig',
                'avg_rating' => 4.0,
                'poster_url' => 'images/posters/barbie.jpg',
                'trailer_url' => 'https://example.com/barbie-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Guardians of the Galaxy',
                'description' => 'A group of intergalactic criminals must pull together to stop a fanatical warrior from taking control of the universe.',
                'year' => '2014',
                'genre' => 'Hài hước, Hành động',
                'director' => 'James Gunn',
                'avg_rating' => 4.5,
                'poster_url' => 'images/posters/guardians.jpg',
                'trailer_url' => 'https://example.com/guardians-trailer.mp4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        foreach ($movies as $movie) {
            DB::table('movies')->insert($movie);
        }
    }
}
